services:
  - type: web
    name: tailorx-api
    env: node
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this in Render dashboard
      - key: GOOGLE_CLIENT_ID
        sync: false  # Set this in Render dashboard
