-- =============================================================================
-- TailorX — Test Users Seed
-- 5 users, each with ALL 38 measurement types (values in mm; shoulderSlope in °)
-- Password for ALL test users: "password"
-- =============================================================================

-- ─── USERS ───────────────────────────────────────────────────────────────────

INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES
  ('lucas.santos@tailorx.test',      '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyWIfHu2S', 'Lucas',   'Santos',    '+56912340001', 'user'),
  ('julia.oliveira@tailorx.test',    '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyWIfHu2S', 'Julia',   'Oliveira',  '+56912340002', 'user'),
  ('martin.ferreira@tailorx.test',   '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyWIfHu2S', 'Martin',  'Ferreira',  '+56912340003', 'user'),
  ('isabela.costa@tailorx.test',     '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyWIfHu2S', 'Isabela', 'Costa',     '+56912340004', 'user'),
  ('pedro.alves@tailorx.test',       '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LPVyWIfHu2S', 'Pedro',   'Alves',     '+56912340005', 'user');

-- ─── MEASUREMENTS ────────────────────────────────────────────────────────────

INSERT INTO user_measurements (user_id, measurement_type_id, value)
SELECT u.id, mt.id, v.value
FROM (VALUES

  -- Image 1 Data
  ('lucas.santos@tailorx.test', 'ankle',               215),
  ('lucas.santos@tailorx.test', 'biceps',              373.02),
  ('lucas.santos@tailorx.test', 'bustFront',           470),
  ('lucas.santos@tailorx.test', 'bustPointToUnderbust',110),
  ('lucas.santos@tailorx.test', 'bustSpan',            190),
  ('lucas.santos@tailorx.test', 'chest',               1045.14),
  ('lucas.santos@tailorx.test', 'crossSeam',           720),
  ('lucas.santos@tailorx.test', 'crossSeamFront',      280),
  ('lucas.santos@tailorx.test', 'crotchDepth',         265),
  ('lucas.santos@tailorx.test', 'heel',                320),
  ('lucas.santos@tailorx.test', 'head',                560),
  ('lucas.santos@tailorx.test', 'highBust',            1069.79),
  ('lucas.santos@tailorx.test', 'highBustFront',       410),
  ('lucas.santos@tailorx.test', 'hips',                1139.62),
  ('lucas.santos@tailorx.test', 'hpsToBust',           103.29),
  ('lucas.santos@tailorx.test', 'hpsToWaistBack',      456.38),
  ('lucas.santos@tailorx.test', 'hpsToWaistFront',     390),
  ('lucas.santos@tailorx.test', 'inseam',              780),
  ('lucas.santos@tailorx.test', 'knee',                503.98),
  ('lucas.santos@tailorx.test', 'neck',                369),
  ('lucas.santos@tailorx.test', 'seat',                1139.62),
  ('lucas.santos@tailorx.test', 'seatBack',            480),
  ('lucas.santos@tailorx.test', 'shoulderSlope',        13),
  ('lucas.santos@tailorx.test', 'shoulderToElbow',     360),
  ('lucas.santos@tailorx.test', 'shoulderToShoulder',  394.01),
  ('lucas.santos@tailorx.test', 'shoulderToWrist',     533.97),
  ('lucas.santos@tailorx.test', 'underbust',           740),
  ('lucas.santos@tailorx.test', 'upperLeg',            570),
  ('lucas.santos@tailorx.test', 'waist',               1111.63),
  ('lucas.santos@tailorx.test', 'waistBack',           350),
  ('lucas.santos@tailorx.test', 'waistToArmpit',       430.36),
  ('lucas.santos@tailorx.test', 'waistToFloor',       886.63),
  ('lucas.santos@tailorx.test', 'waistToHips',         86.07),
  ('lucas.santos@tailorx.test', 'waistToKnee',         496.73),
  ('lucas.santos@tailorx.test', 'waistToSeat',         86.07),
  ('lucas.santos@tailorx.test', 'waistToUnderbust',    100),
  ('lucas.santos@tailorx.test', 'waistToUpperLeg',     168.2),
  ('lucas.santos@tailorx.test', 'wrist',               173),

  -- Image 2 Data
  ('julia.oliveira@tailorx.test', 'ankle',               230),
  ('julia.oliveira@tailorx.test', 'biceps',              300),
  ('julia.oliveira@tailorx.test', 'bustFront',           510),
  ('julia.oliveira@tailorx.test', 'bustPointToUnderbust', 80),
  ('julia.oliveira@tailorx.test', 'bustSpan',            210),
  ('julia.oliveira@tailorx.test', 'chest',              1082.73),
  ('julia.oliveira@tailorx.test', 'crossSeam',           780),
  ('julia.oliveira@tailorx.test', 'crossSeamFront',      320),
  ('julia.oliveira@tailorx.test', 'crotchDepth',         280),
  ('julia.oliveira@tailorx.test', 'heel',                350),
  ('julia.oliveira@tailorx.test', 'head',                580),
  ('julia.oliveira@tailorx.test', 'highBust',            1130.12),
  ('julia.oliveira@tailorx.test', 'highBustFront',       480),
  ('julia.oliveira@tailorx.test', 'hips',               1223.55),
  ('julia.oliveira@tailorx.test', 'hpsToBust',           98.57),
  ('julia.oliveira@tailorx.test', 'hpsToWaistBack',      469.63),
  ('julia.oliveira@tailorx.test', 'hpsToWaistFront',     430),
  ('julia.oliveira@tailorx.test', 'inseam',              830),
  ('julia.oliveira@tailorx.test', 'knee',                644.92),
  ('julia.oliveira@tailorx.test', 'neck',                300),
  ('julia.oliveira@tailorx.test', 'seat',               1223.55),
  ('julia.oliveira@tailorx.test', 'seatBack',            510),
  ('julia.oliveira@tailorx.test', 'shoulderSlope',        10),
  ('julia.oliveira@tailorx.test', 'shoulderToElbow',     380),
  ('julia.oliveira@tailorx.test', 'shoulderToShoulder',  382.22),
  ('julia.oliveira@tailorx.test', 'shoulderToWrist',     527.83),
  ('julia.oliveira@tailorx.test', 'underbust',           920),
  ('julia.oliveira@tailorx.test', 'upperLeg',            580),
  ('julia.oliveira@tailorx.test', 'waist',               1230.52),
  ('julia.oliveira@tailorx.test', 'waistBack',           430),
  ('julia.oliveira@tailorx.test', 'waistToArmpit',       410.72),
  ('julia.oliveira@tailorx.test', 'waistToFloor',       898.46),
  ('julia.oliveira@tailorx.test', 'waistToHips',         82.14),
  ('julia.oliveira@tailorx.test', 'waistToKnee',         502.73),
  ('julia.oliveira@tailorx.test', 'waistToSeat',         82.14),
  ('julia.oliveira@tailorx.test', 'waistToUnderbust',     80),
  ('julia.oliveira@tailorx.test', 'waistToUpperLeg',     166.26),
  ('julia.oliveira@tailorx.test', 'wrist',               150),

  -- Image 3 Data
  ('martin.ferreira@tailorx.test', 'ankle',               250),
  ('martin.ferreira@tailorx.test', 'biceps',              313.93),
  ('martin.ferreira@tailorx.test', 'bustFront',           590),
  ('martin.ferreira@tailorx.test', 'bustPointToUnderbust',130),
  ('martin.ferreira@tailorx.test', 'bustSpan',            220),
  ('martin.ferreira@tailorx.test', 'chest',              1012.2),
  ('martin.ferreira@tailorx.test', 'crossSeam',           820),
  ('martin.ferreira@tailorx.test', 'crossSeamFront',      320),
  ('martin.ferreira@tailorx.test', 'crotchDepth',         275),
  ('martin.ferreira@tailorx.test', 'heel',                340),
  ('martin.ferreira@tailorx.test', 'head',                570),
  ('martin.ferreira@tailorx.test', 'highBust',           1034.88),
  ('martin.ferreira@tailorx.test', 'highBustFront',       510),
  ('martin.ferreira@tailorx.test', 'hips',               1236),
  ('martin.ferreira@tailorx.test', 'hpsToBust',           113.53),
  ('martin.ferreira@tailorx.test', 'hpsToWaistBack',      502.13),
  ('martin.ferreira@tailorx.test', 'hpsToWaistFront',     400),
  ('martin.ferreira@tailorx.test', 'inseam',              760),
  ('martin.ferreira@tailorx.test', 'knee',                499.32),
  ('martin.ferreira@tailorx.test', 'neck',                404.6),
  ('martin.ferreira@tailorx.test', 'seat',               1265.9),
  ('martin.ferreira@tailorx.test', 'seatBack',            610),
  ('martin.ferreira@tailorx.test', 'shoulderSlope',        12),
  ('martin.ferreira@tailorx.test', 'shoulderToElbow',     355),
  ('martin.ferreira@tailorx.test', 'shoulderToShoulder',  420),
  ('martin.ferreira@tailorx.test', 'shoulderToWrist',     558.09),
  ('martin.ferreira@tailorx.test', 'underbust',           920),
  ('martin.ferreira@tailorx.test', 'upperLeg',            680),
  ('martin.ferreira@tailorx.test', 'waist',               1154),
  ('martin.ferreira@tailorx.test', 'waistBack',           490),
  ('martin.ferreira@tailorx.test', 'waistToArmpit',       473.03),
  ('martin.ferreira@tailorx.test', 'waistToFloor',       914.97),
  ('martin.ferreira@tailorx.test', 'waistToHips',         94.61),
  ('martin.ferreira@tailorx.test', 'waistToKnee',         530.82),
  ('martin.ferreira@tailorx.test', 'waistToSeat',         94.61),
  ('martin.ferreira@tailorx.test', 'waistToUnderbust',    110),
  ('martin.ferreira@tailorx.test', 'waistToUpperLeg',     181.85),
  ('martin.ferreira@tailorx.test', 'wrist',               140),

  -- Image 4 Data
  ('isabela.costa@tailorx.test', 'ankle',               245),
  ('isabela.costa@tailorx.test', 'biceps',              354.9),
  ('isabela.costa@tailorx.test', 'bustFront',           540),
  ('isabela.costa@tailorx.test', 'bustPointToUnderbust', 85),
  ('isabela.costa@tailorx.test', 'bustSpan',            220),
  ('isabela.costa@tailorx.test', 'chest',              1061.59),
  ('isabela.costa@tailorx.test', 'crossSeam',           810),
  ('isabela.costa@tailorx.test', 'crossSeamFront',      330),
  ('isabela.costa@tailorx.test', 'crotchDepth',         290),
  ('isabela.costa@tailorx.test', 'heel',                365),
  ('isabela.costa@tailorx.test', 'head',                590),
  ('isabela.costa@tailorx.test', 'highBust',           1107.76),
  ('isabela.costa@tailorx.test', 'highBustFront',       510),
  ('isabela.costa@tailorx.test', 'hips',               1241.78),
  ('isabela.costa@tailorx.test', 'hpsToBust',           108.51),
  ('isabela.costa@tailorx.test', 'hpsToWaistBack',      516.15),
  ('isabela.costa@tailorx.test', 'hpsToWaistFront',     450),
  ('isabela.costa@tailorx.test', 'inseam',              850),
  ('isabela.costa@tailorx.test', 'knee',                535.39),
  ('isabela.costa@tailorx.test', 'neck',                439.44),
  ('isabela.costa@tailorx.test', 'seat',               1241.78),
  ('isabela.costa@tailorx.test', 'seatBack',            520),
  ('isabela.costa@tailorx.test', 'shoulderSlope',        13),
  ('isabela.costa@tailorx.test', 'shoulderToElbow',     395),
  ('isabela.costa@tailorx.test', 'shoulderToShoulder',  420),
  ('isabela.costa@tailorx.test', 'shoulderToWrist',     583.99),
  ('isabela.costa@tailorx.test', 'underbust',           980),
  ('isabela.costa@tailorx.test', 'upperLeg',            620),
  ('isabela.costa@tailorx.test', 'waist',               1190.14),
  ('isabela.costa@tailorx.test', 'waistBack',           410),
  ('isabela.costa@tailorx.test', 'waistToArmpit',       452.11),
  ('isabela.costa@tailorx.test', 'waistToFloor',       910.33),
  ('isabela.costa@tailorx.test', 'waistToHips',         90.42),
  ('isabela.costa@tailorx.test', 'waistToKnee',         521.04),
  ('isabela.costa@tailorx.test', 'waistToSeat',         90.42),
  ('isabela.costa@tailorx.test', 'waistToUnderbust',     80),
  ('isabela.costa@tailorx.test', 'waistToUpperLeg',     176.55),
  ('isabela.costa@tailorx.test', 'wrist',               170),

  -- Image 5 Data
  ('pedro.alves@tailorx.test', 'ankle',               200),
  ('pedro.alves@tailorx.test', 'biceps',              324.66),
  ('pedro.alves@tailorx.test', 'bustFront',           420),
  ('pedro.alves@tailorx.test', 'bustPointToUnderbust',100),
  ('pedro.alves@tailorx.test', 'bustSpan',            170),
  ('pedro.alves@tailorx.test', 'chest',               1075.24),
  ('pedro.alves@tailorx.test', 'crossSeam',           680),
  ('pedro.alves@tailorx.test', 'crossSeamFront',      260),
  ('pedro.alves@tailorx.test', 'crotchDepth',         255),
  ('pedro.alves@tailorx.test', 'heel',                305),
  ('pedro.alves@tailorx.test', 'head',                545),
  ('pedro.alves@tailorx.test', 'highBust',            1176.85),
  ('pedro.alves@tailorx.test', 'highBustFront',       385),
  ('pedro.alves@tailorx.test', 'hips',                1261.39),
  ('pedro.alves@tailorx.test', 'hpsToBust',           121.65),
  ('pedro.alves@tailorx.test', 'hpsToWaistBack',      552.7),
  ('pedro.alves@tailorx.test', 'hpsToWaistFront',     360),
  ('pedro.alves@tailorx.test', 'inseam',              720),
  ('pedro.alves@tailorx.test', 'knee',                508.69),
  ('pedro.alves@tailorx.test', 'neck',                448.31),
  ('pedro.alves@tailorx.test', 'seat',                1261.39),
  ('pedro.alves@tailorx.test', 'seatBack',            450),
  ('pedro.alves@tailorx.test', 'shoulderSlope',        12.93),
  ('pedro.alves@tailorx.test', 'shoulderToElbow',     340),
  ('pedro.alves@tailorx.test', 'shoulderToShoulder',  453.42),
  ('pedro.alves@tailorx.test', 'shoulderToWrist',     669.92),
  ('pedro.alves@tailorx.test', 'underbust',           700),
  ('pedro.alves@tailorx.test', 'upperLeg',            510),
  ('pedro.alves@tailorx.test', 'waist',               1285.69),
  ('pedro.alves@tailorx.test', 'waistBack',           315),
  ('pedro.alves@tailorx.test', 'waistToArmpit',       506.86),
  ('pedro.alves@tailorx.test', 'waistToFloor',       983.91),
  ('pedro.alves@tailorx.test', 'waistToHips',         101.37),
  ('pedro.alves@tailorx.test', 'waistToKnee',         548.36),
  ('pedro.alves@tailorx.test', 'waistToSeat',         101.37),
  ('pedro.alves@tailorx.test', 'waistToUnderbust',     95),
  ('pedro.alves@tailorx.test', 'waistToUpperLeg',     190.77),
  ('pedro.alves@tailorx.test', 'wrist',               173.78)

) AS v(email, freesewing_key, value)
JOIN users             u  ON u.email              = v.email
JOIN measurement_types mt ON mt.freesewing_key    = v.freesewing_key;